### PR TITLE
Add a workaround for Apple Revenue, calculate MRR

### PR DESCRIPTION
**Pull request by birdsarah**
Partially fixes [DVPN-184](https://mozilla-hub.atlassian.net/browse/DVPN-184)

### CODE REVIEW

**Comment by birdsarah** [comment]
There's an alternate version of this where I just make MRR = ARR / 12 and I update ARR to include the new estimated apple amount.

**Comment by birdsarah** [comment]
But I do want to calculate other kinds of MRR (Contraction, ....) so will end up needing to write out these formulas anyway.

**Comment by birdsarah** [comment]
@wwyc would appreciate a review.

**Comment by birdsarah** [comment]
I have reviewed the calculations manually offline to make sure I'm happy with them and they look good to me. Also if apple revenue is taken out of the question they are 1/12 of ARR as you would expect.

**Review by wwyc — APPROVED** [review]

**Pull request merged**
