### PR TITLE
edit sql to avoid overcouting clients on event-based measures

### PR DESCRIPTION
**Pull request by florezita**
Note: editing sql to only provide measures across all colors in the colorways collection (not by individual color). Otherwise, in the event-based measures, we are over-counting user engagement. For example, in the case that one user "explores" or "plays" with multiple colorways in the modal, in the aggregate the one user should count as 1. Previously, the user would count once if it interacted with one colorway and a second time if it interacted with a second colorway.

Checklist for reviewer:

When adding a new derived dataset:
- [ ] Ensure that the data is not available already (fully or partially) and recommend extending an existing dataset in favor of creating new ones. Data may be available in [bigquery-etl repository](https://github.com/mozilla/bigquery-etl), [looker-hub](https://github.com/mozilla/looker-hub) or in [looker-spoke-default](https://github.com/mozilla/looker-spoke-default/tree/e1315853507fc1ac6e78d252d53dc8df5f5f322b).
- [ ] Avoid merging a PR that includes the logic of a [core metric](https://docs.telemetry.mozilla.org/metrics/index.html) or complex business logic. The recommendation is to implement core business logic in bigquery-etl. E.g. The [type of search](https://github.com/mozilla/bigquery-etl/blob/a3e59f90326816a2ecaaa3e9d5b57fe9552f7d70/sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/query.sql#L781) or the [calculation of DAU or visited URIs](https://github.com/mozilla/bigquery-etl/blob/9bca48821a8a0d40b1700cc14ecd8068d132ed06/sql/moz-fx-data-shared-prod/telemetry_derived/firefox_desktop_exact_mau28_by_dimensions_v1/query.sql).
- [ ] Avoid merging code in Looker Explores/Views that implement analysis with multiple lines of code or that will be likely replicated in the future. Instead, aim for extending an existing dataset to include the required logic, and use [Looker aggregates](https://cloud.google.com/looker/docs/aggregate_awareness) to facilitate the analysis.
- [ ] Avoid merging a PR with logic that requires validation and health checks. It is recommended to implement it in bigquery-etl for full test coverage and failure alerts.

### CODE REVIEW

**Comment by florezita** [comment]
Yea-- i don't mind losing the functionality of splitting it by colorway. They are after total DAU and i doubt anyone has made charts.

The only thing extra I need to think about is capturing all the ways that people can interact with exploring or choosing colorways. I only have the entry point being modal here and to have a more complete understading, I do think I should add about:addons and onboarding numbers.

Should I close this pull request, edit and create a new PR for when it is more complete then?

**Comment by irrationalagent** [comment]
I think it makes sense to do it all in one PR but you can continue to use this one if you want

**Comment by irrationalagent** [comment]
I think for your purposes you could use either. Both will fire when a colorway is set, though the `coloways_modal` events contain more detail.

The main reason to use the `coloways_modal` is when you need to distinguish between a colorways being set for the first time (method = `set_colorway`) or changed (method = `change_colorway`). Or, if you need to know whether the colorway was set from about:addons or firefox view (the event `object` will tell you that)

BTW tip: if you want to test when events are generated, you can (e.g.) set the colorway on your own browser then navigate to about:telemetry. then click on the events tab on the left.

**Review by irrationalagent — APPROVED** [review]
looks good to me.

**Pull request merged**
