### PR TITLE
add temporary join to temporary mobile new profiles table.

### PR DESCRIPTION
**Pull request by irrationalagent**
The query for the temp table is [here](https://console.cloud.google.com/bigquery?sq=630180991450:261b6210dc8047da9dfd4e51cbc22efb). It could probably use a look by a DE.

This will allow us to add new profiles to the mobile KPI dash, but we will need to revert/change this back when the clients_first_seen work is totally done. We should also be clear that these numbers could change once that happens.

### CODE REVIEW

**Comment by jklukas** [comment]
> This will allow us to add new profiles to the mobile KPI dash, but we will need to revert/change this back when the clients_first_seen work is totally done. We should also be clear that these numbers could change once that happens.

Is the urgency here sufficient to warrant this solution? Is `loines_temp_mobile_new_profiles_per_day` going to be updated on a regular basis?

**Comment by irrationalagent** [comment]
> > This will allow us to add new profiles to the mobile KPI dash, but we will need to revert/change this back when the clients_first_seen work is totally done. We should also be clear that these numbers could change once that happens.
> 
> Is the urgency here sufficient to warrant this solution? Is `loines_temp_mobile_new_profiles_per_day` going to be updated on a regular basis?

No I wasn't planning to update it. But it allows me to show stakeholders what the new profile section of the dashboard looks like in the meantime. Do we have an ETA for the cfs work?

**Comment by jklukas** [comment]
> Do we have an ETA for the cfs work?

@acmiyaguchi is actively working on getting cfs integrated to the daily and last_seen tables, and I'm reviewing. I'll let him comment on ETA.

**Comment by irrationalagent** [comment]
OK maybe that's soon enough to hold off on this... we have a meeting with stakeholders next tue and like to deliver if possible a working version of the mobile dashboard at that point.

**Comment by acmiyaguchi** [comment]
Ideally, I'd like to integrate the fields by the end of the week, but it may happen on Monday. I'll be updating https://jira.mozilla.com/browse/DS-1424 appropriately.

**Comment by fbertsch** [comment]
Let's hold off on this until EOD, per Anthony. We can merge it in tomorrow if new_profiles is still not ready from the base tables.

**Comment by acmiyaguchi** [comment]
The `baseline_clients_first_seen` tables are available now (and take into account migration pings in fenix). The `first_seen_date` and `is_new_profile` fields also in the `baseline_clients_daily` and `baseline_clients_last_seen` tables.

**Comment by irrationalagent** [comment]
I'm going to close this since we now have the proper first_seen_dates.

thanks again @acmiyaguchi !

**Pull request closed without merging**
